apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-strideiq
  namespace: strideiq
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "REPLACE_WITH_WORKLOAD_IDENTITY_CLIENT_ID"
    keyvaultName: "REPLACE_WITH_KEYVAULT_NAME"
    objects:  |
      array:
        - |
          objectName: database-password
          objectType: secret
          objectVersion: ""
    tenantId: "REPLACE_WITH_TENANT_ID"
  secretObjects:
  - secretName: strideiq-secrets
    type: Opaque
    data:
    - key: DB_PASSWORD
      objectName: database-password
